#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MiniMoneyBook.Resource", IsApplication=true)]

namespace MiniMoneyBook
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000f
			public const int Input1Frag = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int Input2Frag = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int SummaryFrag = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int SummaryFrag2 = 2131034130;
			
			// aapt resource value: 0x7f05001c
			public const int addButton = 2131034140;
			
			// aapt resource value: 0x7f050007
			public const int amountEditText = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int amountTextView = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int categorySpinner = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int categoryTextView = 2131034120;
			
			// aapt resource value: 0x7f05000e
			public const int deleteButton = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int expenseRadioButton = 2131034115;
			
			// aapt resource value: 0x7f050019
			public const int expenseTextView = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int expenseValueTextView = 2131034138;
			
			// aapt resource value: 0x7f050002
			public const int incomeRadioButton = 2131034114;
			
			// aapt resource value: 0x7f050017
			public const int incomeTextView = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int incomeValueTextView = 2131034136;
			
			// aapt resource value: 0x7f050004
			public const int inputDatePicker = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout3 = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout4 = 2131034122;
			
			// aapt resource value: 0x7f05001d
			public const int logButton = 2131034141;
			
			// aapt resource value: 0x7f05000c
			public const int memoEditText = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int memoTextView = 2131034123;
			
			// aapt resource value: 0x7f05001b
			public const int plot_view = 2131034139;
			
			// aapt resource value: 0x7f050001
			public const int radioGroup1 = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public const int submitButton = 2131034125;
			
			// aapt resource value: 0x7f050015
			public const int thisMonthTextView = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int thisMonthValueTextView = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int todayTextView = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int todayValueTextView = 2131034132;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Input1Frag = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Input2Frag = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int InputActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SummaryFrag = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SummaryFrag2 = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int amount = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int category = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int date = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int expense = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int income = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int memo = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int this_month = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int today = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
