#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lab5.Little_Pig.Resource", IsApplication=true)]

namespace Lab5.Little_Pig
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Dice1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Dice2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Dice3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Dice4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Dice5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Dice6 = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050018
			public const int Fragment1 = 2131034136;
			
			// aapt resource value: 0x7f050000
			public const int Fragment2 = 2131034112;
			
			// aapt resource value: 0x7f050016
			public const int buttonEndTurn = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int buttonNewGame = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int buttonRollDie = 2131034133;
			
			// aapt resource value: 0x7f050008
			public const int buttonStartGame = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int editTextPlayer1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int editTextPlayer2 = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int howToPlayTextView = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int imageViewDie = 2131034129;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout2 = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int linearLayout3 = 2131034123;
			
			// aapt resource value: 0x7f050014
			public const int linearLayout4 = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int textPlayer1 = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int textPlayer1Actual = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int textPlayer2 = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int textPlayer2Actual = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int textViewPlayer1Score = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int textViewPlayer1ScoreLabel = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int textViewPlayer2Score = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int textViewPlayer2ScoreLabel = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int textViewPlayersTurn = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int textViewPoint4ThisTurn = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int textViewPoint4ThisTurnLabel = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BackActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragment1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Fragment2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FrontActivity = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int instruction = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
